### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@GleammerRay 

Please check and update.
Please make a temporary build to test new UI.

### CODE REVIEW

**Review by GleammerRay — COMMENTED** [review]
Thank you!

I have just added a `pull_request_review_comment` trigger to my build action, so hopefully this will create your test builds. I may leave another comment in case the action fails.

**Comment by bovirus** [comment]
@GleammerRay


Could you please using the new mutlilanguage installer (.iss file)?

**Comment by GleammerRay** [comment]
That is separate from the `build all` action (hopefully I can get it work in a moment).

**Comment by GleammerRay** [comment]
Of course, as you wish

**Comment by GleammerRay** [comment]
@bovirus Here's your test build. Please provide screenshots from your system. Thank you.

[Passy-v1.4.1-Windows-Installer.zip](https://github.com/GlitterWare/Passy/files/11409517/Passy-v1.4.1-Windows-Installer.zip)

**Comment by bovirus** [comment]
@GleammerRay

I was tested in my configuration befroe to prose teh changes.

These are the screenshot

Exe file properties
image

Installer pages
image

image

image

image

image

Windows program list

image

Program Home

image

**Comment by GleammerRay** [comment]
Brilliant!

Thanks again for your contribution. This localization will be available in the next version (in about a month). Please tell me if you want to be notified for any future additions/changes to the English localization file.

**Comment by bovirus** [comment]
@GleammerRay

To encourage other translator to add other languages I propose you to add info how to add translation to the home of your github page.

@rktfier
@Roschach96

if yiu are interested could you please translate this english 

https://raw.githubusercontent.com/GlitterWare/Passy/main/lib/l10n/app_en.arb

in your native language and post here

Thanks.

**Comment by GleammerRay** [comment]
Sure thing, I will add a `LOCALIZATION.md` informational file.

**Comment by bovirus** [comment]
@GleammerRay

Thanks.

I asked to other guys that are working on MegaBasterd localization if can be interested about Turkish/Hungarian translation for your software.

**Comment by GleammerRay** [comment]
Localization information is now available under https://github.com/GlitterWare/Passy/blob/dev/LOCALIZATION.md.

**Pull request merged**
